version: v0.11.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: false
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/account/settings
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: Kratos
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    webauthn:
      enabled: true
      config:
        passwordless: false
        rp:
          id: 127.0.0.1
          display_name: id.mrogal.ski
          origin: http://127.0.0.1/account/sign-in

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/account/settings
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/account/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/account/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/account/sign-in

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/account/sign-in

    login:
      ui_url: http://127.0.0.1:4455/account/sign-in
      lifespan: 10m
      after:
        webauthn:
          hooks:
            - hook: revoke_active_sessions
        oidc:
          hooks:
            - hook: revoke_active_sessions

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/account/sign-up
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        webauthn:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: trace
  format: json
  leak_sensitive_values: true

secrets:
  cookie:
    - nd8adnaisrg21894rbnsaf7a8fsahbda89erdgt123789rdb8a9gd21egbv829uu
  cipher:
    - 32y198dnakldsa89dnsacxz980chxz1v

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

cookies:
  domain: 127.0.0.1
  path: /
  same_site: Lax

session:
  cookie:
    name: id.mrogal.ski
  whoami:
    required_aal: aal1

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true