version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: false
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/account/settings
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://127.0.0.1:4455/account/settings

  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: id.mrogal.ski
    lookup_secret:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
            provider: github # This defines the app type used for integration. Use 'github' for GitHub OAuth app. Use 'github-app' for GitHub App.
            client_id:  # Replace this with the OAuth2 Client ID provided by GitHub
            client_secret:  # Replace this with the OAuth2 Client Secret provided by GitHub
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gew0KICAgIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwNCiAgfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOw0KICB7DQogICAgaWRlbnRpdHk6IHsNCiAgICAgIHRyYWl0czogew0KICAgICAgICBbaWYgJ2VtYWlsJyBpbiBjbGFpbXMgJiYgY2xhaW1zLmVtYWlsX3ZlcmlmaWVkIHRoZW4gJ2VtYWlsJyBlbHNlIG51bGxdOiBjbGFpbXMuZW1haWwsDQogICAgICB9LA0KICAgIH0sDQogIH0="
            # Alternatively, use an URL:
            # mapper_url: https://storage.googleapis.com/abc-cde-prd/9cac9717f007808bf17f22ce7f4295c739604b183f05ac4afb4
            scope:
              - user:email
    link:
      enabled: true
      config:
        base_url: http://127.0.0.1/account/verification
    code:
      enabled: true
    webauthn:
      enabled: false

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/account/settings
      privileged_session_max_age: 15m
      # required_aal: aal1
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/account/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/account/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/account/sign-in

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/account/sign-in

    login:
      ui_url: http://127.0.0.1:4455/account/sign-in
      lifespan: 10m
      after:
        oidc:
          hooks:
            - hook: require_verified_address

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/account/sign-up
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: session

log:
  level: trace
  format: json
  leak_sensitive_values: true

secrets:
  cookie:
    - nd8adnaisrg21894rbnsaf7a8fsahbda89erdgt123789rdb8a9gd21egbv829uu
  cipher:
    - 32y198dnakldsa89dnsacxz980chxz1v

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

cookies:
  domain: 127.0.0.1
  path: /
  same_site: Lax

session:
  lifespan: 1h
  earliest_possible_extend: 1h
  cookie:
    name: id.mrogal.ski
    persistent: false
    same_site: Lax
  whoami:
    required_aal: aal1

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true